### PR TITLE
Take into account the particularities of PHP-CS-FIXER V2

### PR DESCRIPTION
**Pull request by mmarynich**

### CODE REVIEW

**Comment by mmarynich** [comment]
Hello Pablo @bruli 

I have taken into account the particularities of PHP-CS-FIXER V2.

I have fixed the following errors:

- The "--level" option does not exist
- The rules contain unknown fixers: "PSR0" | "PSR1" | "PSR2" | "SYMFONY"
- Set "@SYMFONY"  does not exist

**Comment by mmarynich** [comment]
@bruli 

Could you create o new release please ?

Best regards,
Mikhail

**Comment by bruli** [comment]
Hi @mmarynich this PR needs a update from PHP-CS-FIXER?.

**Comment by mmarynich** [comment]
Hi Pablo @bruli 

No, this PR doesn't need an update from PHP-CS-FIXER.
The actual code of your project works well with PHP-CS-FIXER v1, but composer.json requires v2. 

Best regards,
Mikhail

**Pull request merged**
