### PR TITLE
Allow to install php-git-hooks globally

### PR DESCRIPTION
**Pull request by tophsic**
If php-git-hooks is installed via `composer global require`, it is
installed in COMPOSER_HOME/vendor directory. So the `autoload.php` path is
different. Besides, bin are installed is COMPOSER_HOME/vendor/bin
directory, that's why I introduced `PHPGITHOOKS_BIN_DIR` constant.

### CODE REVIEW

**Comment by bruli** [comment]
Please, can you fix conflicts?.

**Comment by tophsic** [comment]
Done :smile:

**Comment by bruli** [comment]
I never thought to install with global option. Can you write a how to in README.md file?

**Comment by tophsic** [comment]
I update documentation but not sure it is in the best way because local and global installation are mixed.

What do you thing?

**Comment by tophsic** [comment]
Not exactly related to PR but on actual [README](https://github.com/bruli/php-git-hooks/blob/f1f5ad0558a2bc6ac7ad1e1a1575eba663aa72e1/README.md), you say "After download all repositories, composer ask you about configuration." but if post install and post update script are not set like explained by "Composer configuration in Symfony2 projects." part, dynamic configuration is not played, isn't it? And the post install and post update configuration are not specific to Symfony2 projects, isn't it?

**Comment by bruli** [comment]
bootstrap.php path it's not correct in hooks files.
bootstrap file allways use global configuration and not works in local composer instalation.

[PhpGitHooks\Infrastructure\PhpCsFixer\PhpCsFixerException]               
  Could not open input file: /home/pablo/.composer/vendor/bin/php-cs-fixer  
  Could not open input file: /home/pablo/.composer/vendor/bin/php-cs-fixer

**Comment by tophsic** [comment]
You are right that `boostrap.php` path is not correct if you copy `pre-commit` script from `vendor/bruli/php-git-hooks`. If you create a symbolic link, it should be fine.

```bash
cd .git/hooks
ln -s ../../vendor/bruli/php-git-hooks/hooks/pre-commit ./
```

Do you prefer to keep the copy method? Or to support both?

I am ashamed of such a stupid error. I commit 9a48d91 to fix local install detection.

I did also a mistake when resolving confict. It is fixed by 86f57fc.
I check on `PHPGITHOOKS_BIN_DIR` constant on each file where it is used to allow you to use php-git-hooks on php-git-hooks itself. I had an error instead. 

I can rebase  the branch to make it cleaner.

Can you consider reopen the PR?

**Comment by bruli** [comment]
It's the same mistake.

```bash
 git commit -a         
PHP Warning:  require(/home/pablo/php-git-hooks/.git/hooks/bootstrap.php): failed to open stream: No such file or directory in /home/pablo/php-git-hooks/.git/hooks/pre-commit on line 4
PHP Stack trace:
PHP   1. {main}() /home/pablo/php-git-hooks/.git/hooks/pre-commit:0
PHP Fatal error:  require(): Failed opening required '/home/pablo/php-git-hooks/.git/hooks/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/pablo/php-git-hooks/.git/hooks/pre-commit on line 4
PHP Stack trace:
PHP   1. {main}() /home/pablo/php-git-hooks/.git/hooks/pre-commit:0
```

Hooks files are copied to .git/hooks directory when you run composer install or update, and in this case bootstrap file no exists in this path. You must write bootstrap path from .git/hook path.

Other error.
In bootstrap file $home var is always my home .composer directory path, but I'm installed the library without global  option. Bootstrap code are not detected between local and global instalation.

**Comment by tophsic** [comment]
Ok, I didn't figure out of that part because I configured it manually :wink:.

I will fix that soon and test better.

**Comment by tophsic** [comment]
This should be the good one. I fixed hooks scripts and `bootstrap.php` file.

I test installation in 3 ways:

* locally with call to `PhpGitHooks\\Application\\Composer\\ConfiguratorScript::buildConfig`, hooks are copied to `.git/hooks` directory and path are resolved
* locally with symbolic link
* globally with method described in README

Can you confirm this? I apologise all the mistakes.

**Comment by bruli** [comment]
``` bash
PHP Fatal error:  Class 'PhpGitHooks\Command\QualityCodeTool' not found in /home/pablo/php-git-hooks/.git/hooks/pre-commit on line 18
PHP Stack trace:
PHP   1. {main}() /home/pablo/php-git-hooks/.git/hooks/pre-commit:0

```

**Comment by tophsic** [comment]
I think it is due to the path files I test at the beginning of `pre-commit` and `commit-msg` script? Have you a better idea to require `bootsrap.php` file?

Have you recreated the php-git-hooks configuration? What is the content of `.git/hooks/pre-commit` script, especially the paths I test at the beginning of the file? Does your dependencies are installed in `vendor` directory?

When I install php-git-hooks from scratch and the branch `feature-install-globally` with dynamic configuration, I do not observe this error.

**Comment by bruli** [comment]
Step by step:

``` bash
$ git clone git@github.com:tophsic/php-git-hooks.git
$ cd php-git-hooks
$ git checkout -b feature-install-globally origin/feature-install-globally
$ composer install (this step create kooks)
```
Modify a php file and do commit.

``` bash
git commit -a
PHP Fatal error:  Class 'PhpGitHooks\Command\QualityCodeTool' not found in /home/pablo/php-git-hooks/.git/hooks/pre-commit on line 18
PHP Stack trace:
PHP   1. {main}() /home/pablo/php-git-hooks/.git/hooks/pre-commit:0
```

**Comment by bruli** [comment]
I think you can search bootstrap localy if not exists you can use like composer global,

**Comment by tophsic** [comment]
I tested in another project which depends on php-git-hooks but I forgot php-git-hooks itself.

It should be good finally. I could have copy `bootstrap.php` in `.git/hooks/` directory to avoid code duplication. If you prefer this approch, I will do it later.

**Pull request closed without merging**
