### PR TITLE
Added option to set testsuite to run in phpunit

### PR DESCRIPTION
**Pull request by squirrelito**
I needed this so here is what I did. Looking forward for comments on this piece :)

### CODE REVIEW

**Comment by bruli** [comment]
Can you explain why we need it?.

**Comment by squirrelito** [comment]
Hello
I needed to specify which test suite to run on pre-commit. Use case is when I want to run unit tests only, skipping system, integration etc.

**Comment by bruli** [comment]
I think it's a good idea, but ConfigurationScript not create a entry in php-git-hooks.yml file for this new configuration. It's necesary.

Can you complete it?.

**Comment by squirrelito** [comment]
I would complete it, for sure but can you ellaborate on your idea for the ConfigurationScript ?

**Comment by bruli** [comment]
Added phpunit options in lastest release.

**Pull request closed without merging**
